name: Deploy & Run Glue ETL Pipeline

on:
  push:
    branches: [ "main" ]
    paths: 
      - "glue/**"
      - "infra/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # PHASE 1: Terraform

  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    
    outputs:
      bucket_name: ${{ steps.tf_out.outputs.bucket_name }}
      role_arn:    ${{ steps.tf_out.outputs.role_arn }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create State Bucket if Missing
        id: create-state
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          STATE_BUCKET="steam-analytics-state-${ACCOUNT_ID}"
          echo "BUCKET_NAME=${STATE_BUCKET}" >> $GITHUB_ENV
          
          if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
            echo "Bucket exists."
          else
            aws s3api create-bucket --bucket "$STATE_BUCKET" --region us-east-1
            aws s3api put-bucket-versioning --bucket "$STATE_BUCKET" --versioning-configuration Status=Enabled
          fi

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        env:
          STATE_BUCKET: ${{ env.BUCKET_NAME }}
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=${STATE_BUCKET}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1"
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="github_repo=${{ github.repository }}" \
            -var="data_bucket_name=placeholder" 

      - name: Export Outputs
        id: tf_out
        run: |
          echo "bucket_name=$(terraform output -raw DEPLOY_BUCKET_NAME)" >> $GITHUB_OUTPUT
          echo "role_arn=$(terraform output -raw DEPLOY_ROLE_ARN)" >> $GITHUB_OUTPUT

  
  # PHASE 2: Upload Scripts
  
  upload-scripts:
    name: Upload Glue Scripts
    runs-on: ubuntu-latest
    needs: terraform
    env:
      BUCKET_NAME: ${{ needs.terraform.outputs.bucket_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.terraform.outputs.role_arn }}
          aws-region: us-east-1
      
      - name: Upload Glue scripts
        run: aws s3 sync glue/ s3://${BUCKET_NAME}/glue-scripts/ --delete


  # PHASE 3: Run Glue Jobs
  
  
  run-applications:
    name: Run Applications Job
    runs-on: ubuntu-latest
    needs: [terraform, upload-scripts]
    env:
      BUCKET_NAME: ${{ needs.terraform.outputs.bucket_name }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.terraform.outputs.role_arn }}
          aws-region: us-east-1

      - name: Trigger & Wait
        run: |
          RUN_ID=$(aws glue start-job-run --job-name steam-analytics-applications-job-dev --query JobRunId --output text)
          echo "Started Applications Job: $RUN_ID"
          
          while true; do
            STATUS=$(aws glue get-job-run --job-name steam-analytics-applications-job-dev --run-id $RUN_ID --query JobRun.JobRunState --output text)
            echo "Status: $STATUS"
            if [ "$STATUS" = "SUCCEEDED" ]; then break; fi
            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then exit 1; fi
            sleep 30
          done

  run-reviews:
    name: Run Reviews Job
    runs-on: ubuntu-latest
    needs: [terraform, upload-scripts] 
    env:
      BUCKET_NAME: ${{ needs.terraform.outputs.bucket_name }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.terraform.outputs.role_arn }}
          aws-region: us-east-1

      - name: Trigger & Wait
        run: |
          RUN_ID=$(aws glue start-job-run --job-name steam-analytics-reviews-job-dev --query JobRunId --output text)
          echo "Started Reviews Job: $RUN_ID"
          
          while true; do
            STATUS=$(aws glue get-job-run --job-name steam-analytics-reviews-job-dev --run-id $RUN_ID --query JobRun.JobRunState --output text)
            echo "Status: $STATUS"
            if [ "$STATUS" = "SUCCEEDED" ]; then break; fi
            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then exit 1; fi
            sleep 30
          done

  run-dimensions:
    name: Run Dimensions Job
    runs-on: ubuntu-latest
    needs: [terraform, upload-scripts]
    env:
      BUCKET_NAME: ${{ needs.terraform.outputs.bucket_name }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.terraform.outputs.role_arn }}
          aws-region: us-east-1

      - name: Trigger & Wait
        run: |
          RUN_ID=$(aws glue start-job-run --job-name steam-analytics-dimensions-job-dev --query JobRunId --output text)
          echo "Started Dimensions Job: $RUN_ID"
          
          while true; do
            STATUS=$(aws glue get-job-run --job-name steam-analytics-dimensions-job-dev --run-id $RUN_ID --query JobRun.JobRunState --output text)
            echo "Status: $STATUS"
            if [ "$STATUS" = "SUCCEEDED" ]; then break; fi
            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then exit 1; fi
            sleep 30
          done

  
  # PHASE 4: Run Crawler
  
  run-crawler:
    name: Run Silver Crawler
    runs-on: ubuntu-latest
    needs: [terraform, run-applications, run-reviews, run-dimensions]
    env:
      BUCKET_NAME: ${{ needs.terraform.outputs.bucket_name }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.terraform.outputs.role_arn }}
          aws-region: us-east-1

      - name: Run Crawler
        run: |
          echo "Starting Silver Crawler..."
          aws glue start-crawler --name steam-analytics-silver-crawler-dev
          sleep 10
          while true; do
            STATUS=$(aws glue get-crawler --name steam-analytics-silver-crawler-dev --query Crawler.State --output text)
            echo "Crawler status: $STATUS"
            if [ "$STATUS" = "READY" ]; then echo "Finished!"; break; fi
            sleep 30
          done
